{% set name = "duckdb" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  # (!!) Please also update the git used for OVERRIDE_GIT_DESCRIBE in the build scripts.
  url: https://github.com/duckdb/duckdb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d9be2c6d3a5ebe2b3d33044fb2cb535bb0bd972a27ae38c4de5e1b4caa4bf68d
  patches:
    - 0001-Dynamically-link-the-cli.patch
    - 0001-Remove-code-signature-before-applying-metadata-to-ex.patch
    - 0002-fix-exports.patch

build:
  number: 0
  skip: true  # [win or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - openssl

outputs:
  - name: libduckdb
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("libduckdb", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - openssl
    test:
      commands:
        - test -f $PREFIX/lib/libduckdb${SHLIB_EXT}
  - name: libduckdb-devel
    script: install-headers.sh
    build:
      run_exports:
        - {{ pin_subpackage("libduckdb", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/duckdb.h
  - name: duckdb-cli
    script: install-cli.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - duckdb -version
  - name: duckdb-extension-json
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-httpfs
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
        - openssl
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-autocomplete
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-fts
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-icu
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-inet
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-tpcds
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-tpch
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://duckdb.org/docs/index.html
  dev_url: https://github.com/duckdb/duckdb

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
