{% set name = "duckdb" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
    # (!!) Please also update the git used for OVERRIDE_GIT_DESCRIBE in the build scripts.
  - url: https://github.com/duckdb/duckdb/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 91e55efe2c1627c4432d620ee9d2ffcd72f954699e76d7dab523348a7dfbb00a
    patches:
      - 0001-Dynamically-link-the-cli.patch
      - 0002-Remove-code-signature-before-applying-metadata-to-ex.patch
  - url: https://github.com/duckdb/duckdb-httpfs/archive/8356a9017444f54018159718c8017ff7db4ea756.tar.gz
    sha256: 712052e2def32b75876dd894894ab51fd4e6870a74f9c0411a1f31a9d00af628
    folder: extension/httpfs
  - url: https://github.com/duckdb/duckdb-fts/archive/39376623630a968154bef4e6930d12ad0b59d7fb.tar.gz
    sha256: b29888d124c424e0c4b502a46809f2c40c4575df6c20b0903a5e848fe527df44
    folder: extension/fts
  - url: https://github.com/duckdb/ducklake/archive/f134ad86f2f6e7cdf4133086c38ecd9c48f1a772.tar.gz
    sha256: f4c8dfe078235f900fddb1f5019cc9cf2bf9d9d6b0c0e58a1d1a9060de214c5b
    folder: extension/ducklake

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - icu
    - openssl
    - libcurl

outputs:
  - name: libduckdb
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("libduckdb", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - openssl
        - icu
    test:
      commands:
        - test -f $PREFIX/lib/libduckdb${SHLIB_EXT}
  - name: libduckdb-devel
    script: install-headers.sh
    build:
      run_exports:
        - {{ pin_subpackage("libduckdb", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/duckdb.h
  - name: duckdb-cli
    script: install-cli.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - duckdb -version
        - {{ RECIPE_DIR }}/test-builtin-extensions.sh
      requires:
        - jq
  - name: duckdb-extension-json
    script: noop.sh
    # Empty placeholder package as this now built-in
    # We need to use the same dependencies as in the main build to make it work in cross-compilation
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - exit 0
  - name: duckdb-extension-tpcds
    build:
      binary_relocation: false
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-autocomplete
    script: noop.sh
    # Empty placeholder package as this now built-in
    # We need to use the same dependencies as in the main build to make it work in cross-compilation
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - exit 0
  - name: duckdb-extension-tpcds
    build:
      binary_relocation: false
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-httpfs
    script: install-extension.sh
    build:
      binary_relocation: false
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
        - openssl
        - libcurl
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-fts
    script: install-extension.sh
    build:
      binary_relocation: false
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
        - openssl
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-tpch
    build:
      binary_relocation: false
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-ducklake
    build:
      binary_relocation: false
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - python *
        - macholib
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - {{ RECIPE_DIR }}/test-extension.sh
      requires:
        - duckdb-cli
        - jq

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://duckdb.org/docs/index.html
  dev_url: https://github.com/duckdb/duckdb

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - flaviomartins
